test05.md
Add CSS Basics and move it to task 4 - what is logical by the Front End course by Edx.
=> add task5 and change task 4 and 5

test06.md
=> Adding extra materials to 6 task

test01.md
=> Adding extra material to task 1

test01.md, test02.md, test03.md, test04.md, test05.md
=> Adding extra to task_1 and task_3

test09.md
Асинхронный JavaScript против отложенного
=> Update extra materials

students.md
=> Fixed surname

schedule.md
It was agreed that we skip Mondays and we meet this Wednesday at 19:30.
Please, review and merge.
=> Update schedule till Jan 20

README.md
=> add frontend dictionaries link to README header

students.md
Please, add me to the student list since I have finished all 5 tasks)))
=> Add Vicky Bond to student list

students.md
**Demo** https://masmik.github.io/weather_app.github.io/
**Source** https://github.com/Masmik/kottans_frontend/tree/master/task_10
=> made task_10: Weather app

students.md
Form:
[Source](https://github.com/Andrew-Omelchenko/-checkout-page/)
[Demo](https://andrew-omelchenko.github.io/-checkout-page/)
=> task_11 - done

students.md
demo https://zubrik1.github.io/task11/
source https://github.com/zubrik1/kottans_frontend/tree/master/task11
=> Completed task 11

students.md
task 11 done
[Demo](https://ermondel.github.io/html5-forms/)
[Source](https://github.com/ermondel/html5-forms)
=> task 11 done

students.md
**Task 8**: [Play](https://igorkurkov.github.io/pair-game/) | [Repo](https://github.com/IgorKurkov/pair-game)
**Task 10**: [Demo](https://igorkurkov.github.io/weather-app/) | [Repo](https://github.com/IgorKurkov/weather-app)
=> add 8, 10 tasks' info to students.md table

students.md
=> task 11: HTML5 form done

students.md
=> Update completed task id for Oleksiy Rudenko

task15.md
=> Adds task 15

test16.md
=> Adds test 16

test16.md
=> added link to article about React components lifecycle

README.md, test00.md
When I read README for the first time it was too long for me to find the first task. It's better to split it up to separate file to make _Task 0_ prominent in the repository.
Also, some formatting is fixed.
=> Split-up Task 0 from README

README.md
=> improve grammar and readability

tasks/git-advanced.md
Resolves #89.
Adds **git-advanced** task details and places the file following the directory structure suggested with #97.
Not referred to from any syllabus yet. TBD.
=> tasks/git-advanced: Add v.1 of the task

tasks/html-css-responsive.md
Partially resolves suggestion by @AMashoshyna in #92 (specifically [this comment](https://github.com/kottans/frontend/issues/92#issuecomment-429137981))
=> make flexbox froggy an obligatory task

tasks/linux-cli-http.md
related to issue #96 
includes:
- hexlet free course on command line basics
- RU and UA translations of article on http
=> add RU/UA versions: linux & cli

tasks/git-collaboration.md, tasks/git-intro.md, tasks/js-basics.md, tasks/js-oop.md
related to issue #96 
added materials:
- Hexlet free course Intro to Programming (using JS)
- several materials on JS in Russian and Ukrainian
- good and relatively short video on Git and GitHub
- article on Git in Ukrainian
=> add RU/UA versions for materials on git and JS

README.md, contents.md, tasks/README.md, tasks/app-design-offline.md, tasks/app-design-performance.md, tasks/git-collaboration.md, tasks/git-intro.md, tasks/html-css-intro.md, tasks/html-css-responsive.md, tasks/js-basics.md, tasks/js-dom.md, tasks/js-oop.md, tasks/linux-cli-http.md, tasks/memory-pair-game.md, tasks/weather-app.md
1. Created plan of the course `contents.md`
2. Numbers of tasks are removed
3. Added meaningful links to tasks and link to _Contents_
4. Reviewed formatting of a few tasks
5. Added _Done_ section to last online task with greeting.
@OleksiyRudenko review, please. You can preview course UX at [viktor-yakubiv/kottans-frontend-2019](https://github.com/viktor-yakubiv/kottans-frontend-2019)
=> Re-link and review tasks 0-11

tasks/html-css-intro.md
- Add link to HTML intro from github
- Fix typo in w3schools name
- Add link to gh pages course
=> html-css-intro: Add extra materials

README.md, contents.md, tasks/README.md, tasks/app-design-offline.md, tasks/app-design-performance.md, tasks/git-advanced.md, tasks/git-collaboration.md, tasks/git-intro.md, tasks/html-css-intro.md, tasks/html-css-responsive-layouts.md, tasks/html-css-responsive.md, tasks/html5-forms.md, tasks/js-basics.md, tasks/js-dom.md, tasks/js-oop.md, tasks/js-post-oop.md, tasks/js-pre-oop.md, tasks/linux-cli-http.md, tasks/memory-pair-game.md, tasks/pizza-app-api-auth-routing.md, tasks/pizza-app-canvas.md, tasks/react-redux.md, tasks/react.md, tasks/weather-app.md
Will close https://github.com/kottans/frontend/issues/124
=> Replacing gitter with telegram links

tasks/js-basics.md, tasks/js-dom.md, tasks/js-oop.md
As discussed, this PR adds freecodecamp challenges (split in two parts, 11 and 10 tasks respectively) and codewars challenges (up to 7 kyu inclusively)
related to closed issue #105
=> Add freecodecamp and codewars

tasks/README.md, tasks/app-design-offline.md, tasks/app-design-performance.md, tasks/git-advanced.md, tasks/git-collaboration.md, tasks/git-intro.md, tasks/html-css-intro.md, tasks/html-css-responsive-layouts.md, tasks/html-css-responsive.md, tasks/html5-forms.md, tasks/js-basics.md, tasks/js-dom.md, tasks/js-oop.md, tasks/js-post-oop.md, tasks/js-pre-oop.md, tasks/linux-cli-http.md, tasks/memory-pair-game.md, tasks/pizza-app-api-auth-routing.md, tasks/pizza-app-canvas.md, tasks/react-redux.md, tasks/react.md, tasks/weather-app.md
issue #128 
As discussed in last meeting, this PR 
- removes some gitter chat mentions
- removes Stanford algorithms course as it is out of scope of this course
Also:
- removes link to  old links collection spreadsheet (the document needs update)
=> Gitter links and misc

faq.md
Update links to current chat in faq.md
=> Update links to current chat in faq.md

tasks/js-basics.md
Add links to You-Don't-Know-JS (optional reading)
Partially resolves #96
=> Add links to You-Don't-Know-JS Eng/Rus (optional reading)

contents.md, tasks/README.md
Other minor changes:
- remove unnecessary use of HTML entities
- replace **Under development** with **Under revision** to let readers know that there are tasks
for the Meetup based phase, these are rather revised then created from the scratch
=> Add pre/post-OOP tasks to the course contents.

tasks/js-dom.md, tasks/js-oop.md, tasks/js-post-oop.md, tasks/js-pre-oop.md
- Relink properly the following tasks:
- DOM
- Tiny JS world
- OOP JS
- OOP Exercise
- Offline Web App
- Fix chat links
- Minor wording improvements
=> JS OOP: Relink tasks. Fix chat links. Improve wording

contents.md, tasks/README.md
=> Move weather app to offline phase and restructure technical tasks listing

tasks/js-post-oop.md
I really like this video for its fun and simple explanation of composition and inheritance concepts, so I propose we add it here as an extra material.
=> add composition/inheritance video to extra materials

tasks/git-collaboration.md, tasks/git-intro.md, tasks/html-css-intro.md, tasks/linux-cli-http.md
Reworded instructions for
1. Git Basics
1. Linux CLI
1. Git Collaboration
1. Intro to HTML & CSS
Also other minor changes are made.
Partially resolves #142 
Next step is to complete other tasks evidence instructions based on this PR review.
=> Change instructions on task completion evidences

tasks/app-design-offline.md, tasks/js-oop.md, tasks/js-post-oop.md, tasks/js-pre-oop.md
Tasks affected:
1. pre-OOP
1. Object Oriented JS
1. OOP exercise
1. Offline Web Applications
Partially resolves #142
Next step is to complete remaining tasks evidence instructions.
=> Change instructions on task completion evidences (part 4)

tasks/app-design-performance.md, tasks/friends-app.md, tasks/memory-pair-game.md
Affected tasks:
1. Memory Pair Game
1. Website Performance Optimization
1. Friends App
Finally resolves #142
=> Change instructions on task completion evidences (part 5)

README.md
=> I just can't stop it!

tasks/app-design-offline.md, tasks/app-design-performance.md, tasks/friends-app.md, tasks/git-collaboration.md, tasks/html-css-intro.md, tasks/html-css-responsive.md, tasks/js-basics.md, tasks/js-dom.md, tasks/js-oop.md, tasks/js-post-oop.md, tasks/js-pre-oop.md, tasks/linux-cli-http.md, tasks/memory-pair-game.md
=> add hashtag to task completion template

tasks/html-css-responsive.md
This is an interesting game for understanding how flex-box works!
=> add extra material in responsive web design

tasks/git-collaboration.md
The link added leads to Google Forms based survey in Russian to collect students' feedback based on initial tasks completion.
=> Add link to the survey on General Basics section

contents.md
In 8 task students require code review for a subtask from (1) (arcade game Frogger).
Shouldn't we add to the 8 task "practice" word?
=> contents.md -  Add to 8 task "practice"

tasks/html-css-intro.md
task has no recourses related to git so `git` in the directory name imo doesnt make any sense
=> potential typo fix

tasks/js-dom.md
Feedback from students may help to improve the course.
Please, review.
=> Add a link to the Frontend basics feedback form

tasks/js-basics.md
Add
* note on English letter **Y**
* note on built-in hints as the first student's resort
=> task JS Basics: Add notes on freecodecamp sub-task

tasks/js-pre-oop.md
Students tend to jump into ES6 classes right off at this pre-oop task.
Add a note on using firm knowledge only and promising there is a chance to improve later.
=> Add a note on minimal requirements re A Tiny JS World task

tasks/js-dom.md
Make freecodecamp tasks to complete scope narrower.
Exclude following tasks from the end of tasks list:
- Arguments Optional (function currying)
- Make a Person (OOP)
- Map the Debris (extra math)
=> Update js-dom task

tasks/friends-app.md
Add a link to feedback form re final offline course tasks part
=> Add feedback sub-section re last offline course part (MPG, Friends)

tasks/js-post-oop.md
Add a link to feedback form re OOP
=> Add feedback sub-section re OOP-related course part

students/stage0-finishers.md
The clarification is important to distinguish between TOP-5, TOP-10, TOP-20 performers.
Please, review.
=> Add clarifications on offline course part completion date identification

students/stage0-finishers.md
=> IrynaY finish

tasks/js-basics.md
Add distinct warning on two most frequent and not really obvious students' fails
=> Add warning to js-basics task

README.md
Added some info about what is p2p within the main course.
=> Update readme with p2p description

students/stage0-finishers.md
Added myself to list of finishers :smiley:
=> add new finisher

tasks/js-pre-oop.md
Add a note on sufficiency of `index.js` for code review
=> Update Building a Tiny JS World task

faq.md
We should update FAQ after beginning of both courses
=> Basic update of FAQ

tasks/js-oop.md
Add two links for different roads, And add #p2p-pr-done chat message. Links follow to my repos now, cause changes in anohter repositories hasn't approven yet.
=> Example of task with p2p and regular course homeworks repos

tasks/app-design-offline.md, tasks/app-design-performance.md, tasks/friends-app.md, tasks/git-collaboration.md, tasks/html-css-intro.md, tasks/html-css-responsive.md, tasks/js-basics.md, tasks/js-dom.md, tasks/js-post-oop.md, tasks/js-pre-oop.md, tasks/linux-cli-http.md, tasks/memory-pair-game.md
Since [Pull243](https://github.com/kottans/frontend/pull/243) was merged, here is my tasks description corrections.
=> Updated tasks with p2p descriptions and links

tasks/html-css-popup.md
Add instructions on code review to be in line with other similar practice-only tasks
(e.g. [MPG](https://github.com/kottans/frontend/blob/master/tasks/memory-pair-game.md))
=> Update html-css-popup task with code review instructions

HTAQ.md
@babayK0 did a great job compiling a HTAQ guide for our community.
Just found my own draft of HTAQ abandoned and believe some extras from it can improve community HTAQ guide.
When merged this PR will
- add intro to asking structure
- add asking approaches examples
- add further readings list
- fix intra-document links
- add TOC
- fix formatting
- change some wordings
Please, review.
=> HTAQ addition

tasks/git-intro.md
=> fix broken link

tasks/friends-app.md
The updated link leads to the newer documentation
old link 
new link
=> UPD the link to XMLHttpRequest, previous is depricated

tasks/linux-cli-http.md
A course from CodeAcademy now offers a trial that becomes a subscription automatically.
Suggested replacement is totally free and offers even deeper insight into Linux CLI
=> tasks/linux-cli.md: Replace CodeAcademy with LinuxSurvival

tasks/linux-cli-http.md
Hi! The typo was found in the header.
=> Typo was found

tasks/git-advanced.md, tasks/html5-forms.md, tasks/react-redux.md, tasks/react.md, tasks/weather-app.md
Hi, @OleksiyRudenko,  please check [HTML5 Forms module](https://github.com/kottans/frontend/blob/master/tasks/html5-forms.md) as an example of resolved issue "Add links to related youtube casting #276"
=> added links to youtube videos in HTML5 module

tasks/react.md
Add an API to supplement Star Wars API with images
=> Update react.md with SW Imagery API

students/stage0-finishers.md
[kottans-frontend](https://github.com/ArthurGorbenko/kottans-frontend)
=> Update stage 0 finishers

tasks/app-design-offline.md
Updated links since old ones didn't work
=> docs: update links in app-design-offline.md

README.md
Hey guys, I dared to make some minor changes in text: edited misspelling, redundant colons, a/the confusions, etc. Will be cool, if it helps you.
=> Edited the text

tasks/html-css-responsive.md
=> Change link to Flexbox Zombies game

tasks/git-intro.md
Extended instructions for the pool request
=> Git and GitHub task description update

tasks/html-css-responsive.md
Hi!
I noticed that the text is duplicated:
1. Lines 12-13 repeat lines 28-30.
2. Line 15 duplicates line 36.
This is confusing because the order in the instructions is out of order.
=> removed confusing extra text

students/stage0-finishers.md
We need finalists' Telegram usernames to contact them beyond general course students chat
=> (stage0-finishers): add instructions on telegram profile link

students/stage0-finishers.md
=> update finishers list

tasks/html-css-responsive.md
Please, consider adding this short article.
The part about different types of pixels was pretty difficult to understand but this article helped me a lot.
=> Add an aditional article to rwd task

tasks/html-css-popup.md
There are some recommendations for the students before starting their work with this [task](https://github.com/kottans/frontend/blob/master/tasks/html-css-popup.md)
=> feat: added recommendations for html-css-popup task

tasks/js-pre-oop.md
Adding requirements and hints re properties listing and Array methods usage to address the most common issues in code submitted by the students.
=> task(js-pre-oop): Add requirements and hints

students/stage0-finishers.md
Hello! I finished 2 optional task and add it there) please, approve.
=> Add optionals tasks

students/stage0-finishers.md
=> Updated stage0-finishers.md

tasks/js-post-oop.md
Adding requirements and hints re OOP/SOLID to address the most common issues in code submitted by the students.
[Doc render preview](https://github.com/kottans/frontend/blob/425e4508152e777379109fa3a3af2572ccbd7cae/tasks/js-post-oop.md)
=> task(js-post-oop): Add requirements

tasks/linux-cli-http.md
Please, consider adding this short video as the pre-reading part for [this article](https://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177). It can help a complete beginners just to have an idea how HTTP works in simple words before diving into more details 😸
=> add video to linux cli task 

tasks/linux-cli-http.md
Please, consider adding following material
=> Added link to article about http (Issue #309)

tasks/linux-cli-http.md
Please consider following material for adding
=> Added link to comics about DNS (issue #309)

SCHEDULE.md
Add advance schedule for edit and fill by potential lectors and admins
=> Add advance schedule

SCHEDULE.md
- Callbacks
- Promises and Async Await
- Generators
=> Added myself for three lectures

SCHEDULE.md
Wrap author name (my) into link to GitHub profile
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Wrap author name (my) into link to GitHub profile

SCHEDULE.md
we don't have anyone like @roman01la who will teach us TS, so let's skip this part?
=> remove TypeScript pack

faq.md
These better links allow to roam through Github Pages auto-generated html files without falling to github interface (as current ones do).
=> Better links in FAQ

README.md
Fixing #404 with adding link to a buddy search chat.
=> Fixing issue #404

tasks/js-oop-frogger.md, tasks/js-oop.md
This task is actually a minimally tweaked original project description.
All resources linked (video, tech requirements, repo) are publicly accessible.
We may want to translate `js-oop-frogger.md` and, possibly, original tech requirements to Ukrainian at some point.
Motivation:
- seeing gap in [tasks progress](https://github.com/kottans/frontend-2022-homeworks/blob/main/stats/pr-stats.md) just breaks my heart
- students will have a nice and visually appealing project on their portfolios
- students will learn SOLID and OOP principles (also DRY and KISS if haven't yet)
Please review.
Resolves #411 
P.S. We may also encourage students to change imagery to make the games more diverse. Some will make it to our twitter
=> JS OOP: add Frogger practice

tasks/git-intro.md
Whole `git remote add upstream https://github.com/kottans/mock-repo.git` is code that should be entered to command line
=> Fixed markdown

tasks/js-basics.md
In freecodecamp task "Write Concise Declarative Functions with ES6"
is 17.
=> Edit task number of JS ES6 features.
